# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_HydHf594TdmrTSPlPPrAgtQaDYanahz
"""

"""Ejercicios
Realice un programa que pida la edad de una persona en años. Si la edad es mayor o igual a 18, el programa debe imprimir la cadena: ‘ADULTO’. Si la edad es menor a 18 se debe imprimir: ‘MENOR DE EDAD’.

Diseñe un algoritmo que determine si ún número es o no es, par positivo.

Diseñe un algoritmo que lea un número de tres cifras y determine si es igual al revés del número.
"""

#1
#edad =int(input("Ingrese su edad: "))
def mayorEdad(edad):
  if edad > 18:
    print('ADULTO')
  else:
    print('MENOR DE EDAD')
#2
#numero = int(input("Ingrese un numero: "))

def esPar(numero):
  return numero %2 == 0

#3
numero = str(404)

def esPalíndromo(numero):
    posicion_final = len(numero) -1
    resultado = ''

    #reversando
    for i in range(posicion_final,-1,-1):
      resultado+=numero[i]

    return numero == resultado

#esPalíndromo(numero)
#mayorEdad(edad)
#esPar(2)